#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
# File Options
files:
  include: '*.s+(a|c)ss'
# Rule Configuration
rules:
  class-name-format: 0
  variable-name-format: 0
  mixin-name-format: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  nesting-depth: 0
  clean-import-paths:
  - 0
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 1
  mixins-before-declarations:
    - 0
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 1
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 0
    -
      size: 2
  property-sort-order:
    - 0
    -
      ignore-custom-properties: true

  # Allow empty lines between blocks and single line rulesets
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/empty-line-between-blocks.md
  empty-line-between-blocks:
  - 1
  -
      allow-single-line-rulesets: true
      
  # Need to enable these vendor prefixes so that it will allow -ms-high-contrast and -webkit-overflow-scrolling
  # Would be best to find a way to exclude only those specific properties, not all prefixed properties
  no-vendor-prefixes:
  - 1
  -
    excluded-identifiers:
      - 'ms'
      - 'webkit'
      
  # Enforce hex codes to full length
  hex-length:
  - 1
  - style: long
  
  # Allow properties that are unrecognized by the linter
  no-misspelled-properties:
  - 1
  -
    extra-properties:
      - 'overflow-scrolling'
